#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# Adds (or replaces) one release in the Sparkle appcast that GitHub Pages serves.
# The release job calls this after it has signed the zip; everything comes in
# through the environment so there's nothing to quote on the command line.
#
# Env:
#   APPCAST        path to the appcast file to update (created if missing)
#   TITLE          item title (the tag, e.g. v2026-06-19.1)
#   VERSION        CFBundleVersion, the value Sparkle compares (e.g. 20260619.1)
#   SHORT_VERSION  CFBundleShortVersionString shown to the user (e.g. 0.1.0)
#   URL            download URL of the zip (the GitHub release asset)
#   SIGNATURE      EdDSA signature from sign_update
#   LENGTH         zip size in bytes from sign_update
#   MIN_SYSTEM     minimum macOS version (e.g. 14.0)
#   PUBDATE        RFC-822 date string
#   NOTES          release notes (Markdown source; shown as plain text in-app)

import os
# Parses only our own appcast, regenerated by this script and committed to the
# repo, never attacker-controlled input, so the stdlib parser is fine here and
# avoids a CI dependency. The release notes go in as element text, not parsed.
import xml.etree.ElementTree as ET

SPARKLE = "http://www.andymatuschak.org/xml-namespaces/sparkle"
ET.register_namespace("sparkle", SPARKLE)


def sparkle(tag):
    return f"{{{SPARKLE}}}{tag}"


def load_or_create(path):
    if os.path.exists(path):
        return ET.parse(path)
    rss = ET.Element("rss", {"version": "2.0"})
    channel = ET.SubElement(rss, "channel")
    ET.SubElement(channel, "title").text = "Pass Quick Access"
    return ET.ElementTree(rss)


def main():
    env = os.environ
    path = env["APPCAST"]
    tree = load_or_create(path)
    channel = tree.getroot().find("channel")

    # Drop any existing item for this version, so re-running a release is safe.
    for item in channel.findall("item"):
        version = item.findtext(sparkle("version"))
        if version == env["VERSION"]:
            channel.remove(item)

    item = ET.Element("item")
    ET.SubElement(item, "title").text = env["TITLE"]
    ET.SubElement(item, "pubDate").text = env["PUBDATE"]
    ET.SubElement(item, sparkle("version")).text = env["VERSION"]
    ET.SubElement(item, sparkle("shortVersionString")).text = env["SHORT_VERSION"]
    ET.SubElement(item, sparkle("minimumSystemVersion")).text = env["MIN_SYSTEM"]
    ET.SubElement(item, "description").text = env.get("NOTES", "")
    ET.SubElement(item, "enclosure", {
        "url": env["URL"],
        sparkle("edSignature"): env["SIGNATURE"],
        "length": env["LENGTH"],
        "type": "application/octet-stream",
    })

    # Newest first.
    title = channel.find("title")
    channel.insert(list(channel).index(title) + 1, item)

    ET.indent(tree, space="  ")
    tree.write(path, encoding="UTF-8", xml_declaration=True)


if __name__ == "__main__":
    main()
